[package]
name = "nihongoc"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
itertools = "0.13.0"
regex = "1.10.6"
strum_macros = "0.26.4"
strum = "0.26.3"
reserved_proc_macro = { path = "reserved_proc_macro" }
